// EEAT content audit (standalone, dependency-free).
//
// Scores every published article against the CryptoWatchdog EEAT bar:
//   - 2,000+ words of body content
//   - at least one image (hero, gallery, or inline)
//   - at least one internal link (to another CryptoWatchdog page)
//   - at least one external / citation link (research, sources, regulators)
//   - clear structure (multiple H2/H3 sections)
//
// Read-only. Reads local snapshot JSON, writes a report + CSV, prints a digest.
// Run: node scripts/audit_eeat.mjs   (from the cw-content-brain directory)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

const SNAP = "data/content_snapshot";
const OUT = "data/reports";
const SITE_HOSTS = ["cryptowatchdog.net", "www.cryptowatchdog.net"];

const RULES = {
  minWords: 2000,
  minImages: 1,
  minInternalLinks: 1,
  minExternalLinks: 1,
  minHeadings: 3,
};

// ---------- text helpers ----------
const readJson = (p) => JSON.parse(readFileSync(p, "utf8"));

function stripToText(md = "") {
  return md
    .replace(/```[\s\S]*?```/g, " ")          // code fences
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")     // images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")   // links -> keep anchor text
    .replace(/<[^>]+>/g, " ")                  // html tags
    .replace(/[#>*_`~|-]/g, " ")               // md punctuation
    .replace(/\s+/g, " ")
    .trim();
}

const countWords = (txt) => (txt ? txt.split(/\s+/).filter(Boolean).length : 0);

function inlineImages(md = "") {
  return (md.match(/!\[[^\]]*\]\([^)]*\)/g) || []).length +
         (md.match(/<img\b/gi) || []).length;
}

function links(md = "") {
  const urls = [];
  for (const m of md.matchAll(/\[[^\]]*\]\(([^)\s]+)/g)) urls.push(m[1]);
  for (const m of md.matchAll(/<a\b[^>]*href=["']([^"']+)/gi)) urls.push(m[1]);
  for (const m of md.matchAll(/(?<!["'(])\bhttps?:\/\/[^\s)<>"']+/g)) urls.push(m[0]);
  let internal = 0, external = 0;
  for (let u of urls) {
    u = u.trim();
    if (!u || u.startsWith("#")) continue;
    if (u.startsWith("/") || u.startsWith("./") || u.startsWith("../")) { internal++; continue; }
    const host = (u.match(/^https?:\/\/([^/]+)/) || [])[1];
    if (!host) continue;
    if (SITE_HOSTS.some((h) => host === h || host.endsWith("." + h))) internal++;
    else external++;
  }
  return { internal, external };
}

const countHeadings = (md = "") => (md.match(/^#{2,6}\s+/gm) || []).length;

// collect any string/array-of-strings/object values recursively (for reviews' rich fields)
function deepText(value, acc) {
  if (value == null) return;
  if (typeof value === "string") { acc.push(value); return; }
  if (Array.isArray(value)) { value.forEach((v) => deepText(v, acc)); return; }
  if (typeof value === "object") { Object.values(value).forEach((v) => deepText(v, acc)); }
}

// ---------- per-type normalisers ----------
function normalise(type, row) {
  let bodyMd = "", imageFields = 0, extraText = [];
  if (type === "blog_posts") {
    bodyMd = row.content || "";
    if (row.image_url) imageFields++;
  } else if (type === "warnings") {
    bodyMd = row.content || "";
    deepText(row.details, extraText);
  } else if (type === "reviews") {
    // reviews are structured: gather every text-bearing field
    const parts = [row.summary, row.verdict, row.fees_info, row.withdrawal_info, row.deposit_info];
    deepText(row.detailed_audit, parts);
    deepText(row.rich_content, parts);
    deepText(row.nutshell, parts);
    deepText(row.audit_breakdown, parts);
    deepText(row.verdict_block, parts);
    deepText(row.pros, parts);
    deepText(row.cons, parts);
    bodyMd = parts.filter(Boolean).join("\n\n");
    if (row.logo_url) imageFields++;
    if (row.social_image_url) imageFields++;
    if (Array.isArray(row.gallery)) imageFields += row.gallery.length;
  }
  const combined = bodyMd + "\n" + extraText.join("\n");
  const lk = links(combined);
  return {
    type,
    slug: row.slug,
    title: row.title || row.name || row.platform_name || row.slug,
    published: row.published !== false,
    words: countWords(stripToText(combined)),
    images: imageFields + inlineImages(combined),
    internal: lk.internal,
    external: lk.external,
    headings: countHeadings(bodyMd),
    autoGenerated: row.auto_generated === true,
    updated_at: row.updated_at,
  };
}

// ---------- scoring ----------
function assess(r) {
  const fails = [];
  if (r.words < RULES.minWords) fails.push(`words ${r.words}/${RULES.minWords}`);
  if (r.images < RULES.minImages) fails.push("no images");
  if (r.internal < RULES.minInternalLinks) fails.push("no internal links");
  if (r.external < RULES.minExternalLinks) fails.push("no external/citation links");
  if (r.headings < RULES.minHeadings) fails.push(`thin structure (${r.headings} headings)`);

  // 0-100 EEAT score: words 40, images 15, internal 15, external 20, structure 10
  const wScore = Math.min(1, r.words / RULES.minWords) * 40;
  const iScore = r.images >= RULES.minImages ? 15 : 0;
  const inScore = Math.min(1, r.internal / 3) * 15;
  const exScore = Math.min(1, r.external / 3) * 20;
  const sScore = Math.min(1, r.headings / RULES.minHeadings) * 10;
  const score = Math.round(wScore + iScore + inScore + exScore + sScore);
  return { ...r, fails, failCount: fails.length, score, pass: fails.length === 0 };
}

// ---------- run ----------
const records = [];
for (const type of ["blog_posts", "warnings", "reviews"]) {
  const p = `${SNAP}/${type}.json`;
  if (!existsSync(p)) continue;
  for (const row of readJson(p)) records.push(assess(normalise(type, row)));
}

const published = records.filter((r) => r.published);
published.sort((a, b) => a.score - b.score || b.failCount - a.failCount);

const tally = (pred) => published.filter(pred).length;
const summary = {
  generatedAt: new Date().toISOString(),
  rules: RULES,
  totalPublished: published.length,
  passing: tally((r) => r.pass),
  failing: tally((r) => !r.pass),
  under2kWords: tally((r) => r.words < RULES.minWords),
  noImages: tally((r) => r.images < 1),
  noInternalLinks: tally((r) => r.internal < 1),
  noExternalLinks: tally((r) => r.external < 1),
  thinStructure: tally((r) => r.headings < RULES.minHeadings),
  byType: Object.fromEntries(["blog_posts", "warnings", "reviews"].map((t) => {
    const g = published.filter((r) => r.type === t);
    return [t, { total: g.length, passing: g.filter((r) => r.pass).length }];
  })),
};

mkdirSync(OUT, { recursive: true });
writeJsonReport();
writeCsv();
writeMarkdown();
printDigest();

function writeJsonReport() {
  writeFileSync(`${OUT}/eeat_audit.json`, JSON.stringify({ summary, items: published }, null, 2));
}
function writeCsv() {
  const head = "score,type,slug,title,words,images,internal,external,headings,fails";
  const rows = published.map((r) =>
    [r.score, r.type, r.slug, JSON.stringify(r.title), r.words, r.images, r.internal, r.external, r.headings, JSON.stringify(r.fails.join("; "))].join(","));
  writeFileSync(`${OUT}/eeat_audit.csv`, [head, ...rows].join("\n"));
}
function writeMarkdown() {
  const L = [];
  L.push(`# EEAT Content Audit — CryptoWatchdog`);
  L.push(`Generated ${summary.generatedAt}`);
  L.push(``);
  L.push(`**Bar:** ${RULES.minWords}+ words · ≥1 image · ≥1 internal link · ≥1 external/citation link · ${RULES.minHeadings}+ section headings`);
  L.push(``);
  L.push(`| Metric | Count | of ${summary.totalPublished} published |`);
  L.push(`|---|---|---|`);
  L.push(`| ✅ Fully passing EEAT | ${summary.passing} | ${pct(summary.passing)} |`);
  L.push(`| ❌ Failing one or more | ${summary.failing} | ${pct(summary.failing)} |`);
  L.push(`| Under ${RULES.minWords} words | ${summary.under2kWords} | ${pct(summary.under2kWords)} |`);
  L.push(`| No images | ${summary.noImages} | ${pct(summary.noImages)} |`);
  L.push(`| No internal links | ${summary.noInternalLinks} | ${pct(summary.noInternalLinks)} |`);
  L.push(`| No external/citation links | ${summary.noExternalLinks} | ${pct(summary.noExternalLinks)} |`);
  L.push(`| Thin structure | ${summary.thinStructure} | ${pct(summary.thinStructure)} |`);
  L.push(``);
  L.push(`## Worst offenders first (full ranked list)`);
  L.push(``);
  L.push(`| # | Score | Type | Title | Words | Img | Int | Ext | Missing |`);
  L.push(`|---|---|---|---|---|---|---|---|---|`);
  published.forEach((r, i) => {
    L.push(`| ${i + 1} | ${r.score} | ${r.type.replace("_", " ")} | ${trunc(r.title, 60)} | ${r.words} | ${r.images} | ${r.internal} | ${r.external} | ${r.fails.join("; ") || "—"} |`);
  });
  writeFileSync(`${OUT}/eeat_audit.md`, L.join("\n"));
}
function pct(n) { return summary.totalPublished ? Math.round((n / summary.totalPublished) * 100) + "%" : "0%"; }
function trunc(s, n) { s = String(s).replace(/\|/g, "/"); return s.length > n ? s.slice(0, n - 1) + "…" : s; }

function printDigest() {
  console.log(`\nEEAT AUDIT — ${summary.totalPublished} published items`);
  console.log(`  bar: ${RULES.minWords}+ words, image, internal link, external/citation link, ${RULES.minHeadings}+ headings`);
  console.log(`  PASS all rules:        ${summary.passing}`);
  console.log(`  FAIL >=1 rule:         ${summary.failing}`);
  console.log(`  under ${RULES.minWords} words:        ${summary.under2kWords}`);
  console.log(`  no images:             ${summary.noImages}`);
  console.log(`  no internal links:     ${summary.noInternalLinks}`);
  console.log(`  no external citations: ${summary.noExternalLinks}`);
  console.log(`  thin structure:        ${summary.thinStructure}`);
  console.log(`  by type:`, JSON.stringify(summary.byType));
  console.log(`\n  Worst 15:`);
  published.slice(0, 15).forEach((r, i) => {
    console.log(`   ${String(i + 1).padStart(2)}. [${String(r.score).padStart(3)}] ${r.type.padEnd(11)} ${trunc(r.title, 48).padEnd(49)} w=${String(r.words).padStart(4)} img=${r.images} int=${r.internal} ext=${r.external}`);
  });
  console.log(`\n  Reports: ${OUT}/eeat_audit.md , .csv , .json`);
}
